# Generated by Django 4.1.7 on 2023-06-15 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_products_specification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='des',
        ),
        migrations.AlterField(
            model_name='products',
            name='name',
            field=models.CharField(max_length=1000),
        ),
    ]
