# Generated by Django 4.1.7 on 2023-06-19 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_products_des_alter_products_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=1000)),
                ('image', models.ImageField(upload_to='uploads/images')),
                ('specification', models.TextField(max_length=5000)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
