# Generated by Django 4.1.7 on 2023-06-20 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_carts'),
    ]

    operations = [
        migrations.AddField(
            model_name='carts',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='carts',
            name='image',
            field=models.CharField(max_length=200),
        ),
    ]
